name: Test Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y bats
      - name: Download Hashicorp GPG key
        run: gpg --keyserver keyserver.ubuntu.com --recv-keys 51852D87348FFC4C
      - name: Generate the package
        run: make fetch && make generate && make docker/build
        env:
          PACKAGE: terraform
          VERSION: "0.12.24"
      - name: Run the Bats tests
        run: bats --tap *.bats
        env:
          PACKAGE: terraform
          VERSION: "0.12.24"
